name: Build and Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.12"
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip build tox
      - name: Build
        run: python -m build
      - name: Test
        run: tox --installpkg dist/*.whl
